Resources:
  LambdaCognitoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-lambda-role
      Path: /
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonCognitoPowerUser
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
  UserAPILogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/api-gateway/${UserAPI}
      RetentionInDays: 7
  UserAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: UserAPI
      StageName: paid
      Variables:
        alias: paid
      OpenApiVersion: 3.1.0
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /cognito/signup:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignUp.Arn}/invocations
              responses: {}
          /cognito/signup/confirm:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmSignUp.Arn}/invocations
              responses: {}
          /cognito/token/refresh:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TokenRefresh.Arn}/invocations
              responses: {}
          /cognito/sign-in:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignIn.Arn}/invocations
              responses: {}
          /cognito/sign-out:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignOut.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt UserAPILogsGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller", "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath", "status":"$context.status",
          "responseLength":"$context.responseLength" }'
      ApiKeySourceType: HEADER
      Auth:
        ApiKeyRequired: true
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type, X-Amz-Date, Authorization, X-Api-Key,
          X-Amz-Security-Token'''
        AllowMethods: '''*'''
        MaxAge: 600
  SignUp:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SignUp
      CodeUri: src/SignUp
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Events:
        UserAPIPOSTcognitosignup:
          Type: Api
          Properties:
            Path: /cognito/signup
            Method: POST
            RestApiId: !Ref UserAPI
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
  SignUpLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SignUp}
      RetentionInDays: 7
  ConfirmSignUp:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ConfirmSignUp
      CodeUri: src/ConfirmSignUp
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAPIPOSTcognitosignupconfirm:
          Type: Api
          Properties:
            Path: /cognito/signup/confirm
            Method: POST
            RestApiId: !Ref UserAPI
  ConfirmSignUpLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ConfirmSignUp}
      RetentionInDays: 7
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetUser
      CodeUri: src/GetUser
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAuthorizedAPIPOSTcognitouserdetail:
          Type: Api
          Properties:
            Path: /cognito/user/detail
            Method: POST
            RestApiId: !Ref UserAuthorizedAPI
  GetUserLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetUser}
      RetentionInDays: 7
  UserAuthorizedAPILogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/api-gateway/${UserAuthorizedAPI}
      RetentionInDays: 7
  UserAuthorizedAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: UserAuthorizedAPI
      StageName: paid
      Variables:
        alias: paid
      OpenApiVersion: 3.1.0
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /cognito/user/detail:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetUser.Arn}/invocations
              responses: {}
          /cognito/user/attributes/edit:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateAttributes.Arn}/invocations
              responses: {}
          /cognito/user/attributes/verify:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VerifyAttribute.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt UserAuthorizedAPILogsGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller", "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath", "status":"$context.status",
          "responseLength":"$context.responseLength" }'
      Auth:
        Authorizers:
          Cognito:
            UserPoolArn: !ImportValue userPoolArn
        DefaultAuthorizer: Cognito
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type, X-Amz-Date, Authorization, X-Api-Key,
          X-Amz-Security-Token'''
        AllowMethods: '''*'''
        MaxAge: 600
  SignInFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref SignIn
      Description: v1.2
  SignUpFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref SignUp
      Description: v1.2
  ConfirmSignUpFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ConfirmSignUp
      Description: v1.2
  SignOutFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref SignOut
      Description: v1.2
  GetUserFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref GetUser
      Description: v1.2
  SignInFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignIn
      FunctionVersion: !GetAtt SignInFixVersion.Version
      Name: free
  SignInPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignIn
      FunctionVersion: $LATEST
      Name: paid
  SignUpFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignUp
      FunctionVersion: !GetAtt SignUpFixVersion.Version
      Name: free
  SignUpPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignUp
      FunctionVersion: $LATEST
      Name: paid
  ConfirmSignUpFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ConfirmSignUp
      FunctionVersion: !GetAtt ConfirmSignUpFixVersion.Version
      Name: free
  ConfirmSignUpPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref ConfirmSignUp
      FunctionVersion: $LATEST
      Name: paid
  SignOutFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignOut
      FunctionVersion: !GetAtt SignOutFixVersion.Version
      Name: free
  SignOutPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref SignOut
      FunctionVersion: $LATEST
      Name: paid
  GetUserFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref GetUser
      FunctionVersion: !GetAtt GetUserFixVersion.Version
      Name: free
  GetUserPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref GetUser
      FunctionVersion: $LATEST
      Name: paid
  UserAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref UserAPI
      Description: UserAPI deployment
  UserAuthorizedAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref UserAuthorizedAPI
      Description: UserAuthorizedAPI deployment
  UserAPIFreeStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref UserAPI
      StageName: free
      Description: Free stage
      DeploymentId: !GetAtt UserAPIDeployment.DeploymentId
      Variables:
        alias: free
      AccessLogSetting:
        DestinationArn: !GetAtt UserAPILogsGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller", "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath", "status":"$context.status",
          "responseLength":"$context.responseLength" }'
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: true
          LoggingLevel: INFO
  UserAuthorizedAPIFreeStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref UserAuthorizedAPI
      StageName: free
      Description: Free stage
      DeploymentId: !GetAtt UserAuthorizedAPIDeployment.DeploymentId
      Variables:
        alias: free
      AccessLogSetting:
        DestinationArn: !GetAtt UserAuthorizedAPILogsGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller", "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath", "status":"$context.status",
          "responseLength":"$context.responseLength" }'
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: true
          LoggingLevel: INFO
  TokenRefresh:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: TokenRefresh
      CodeUri: src/TokenRefresh
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAPIPOSTcognitotokenrefresh:
          Type: Api
          Properties:
            Path: /cognito/token/refresh
            Method: POST
            RestApiId: !Ref UserAPI
  TokenRefreshLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TokenRefresh}
      RetentionInDays: 7
  TokenRefreshFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref TokenRefresh
      Description: v1.2
  TokenRefreshFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref TokenRefresh
      FunctionVersion: !GetAtt TokenRefreshFixVersion.Version
      Name: free
  TokenRefreshPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref TokenRefresh
      FunctionVersion: $LATEST
      Name: paid
  UpdateAttributesFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref UpdateAttributes
      Description: v1.0
  UpdateAttributesFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref UpdateAttributes
      FunctionVersion: !GetAtt UpdateAttributesFixVersion.Version
      Name: free
  UpdateAttributesPaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref UpdateAttributes
      FunctionVersion: $LATEST
      Name: paid
  VerifyAttributeFixVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref VerifyAttribute
      Description: v1.0
  VerifyAttributeFreeAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref VerifyAttribute
      FunctionVersion: !GetAtt VerifyAttributeFixVersion.Version
      Name: free
  VerifyAttributePaidAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref VerifyAttribute
      FunctionVersion: $LATEST
      Name: paid
  SignIn:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SignIn
      CodeUri: src/SignIn
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAPIPOSTcognitosignin:
          Type: Api
          Properties:
            Path: /cognito/sign-in
            Method: POST
            RestApiId: !Ref UserAPI
  SignInLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SignIn}
      RetentionInDays: 7
  SignOut:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SignOut
      CodeUri: src/SignOut
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAPIPOSTcognitosignout:
          Type: Api
          Properties:
            Path: /cognito/sign-out
            Method: POST
            RestApiId: !Ref UserAPI
  SignOutLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SignOut}
      RetentionInDays: 7
  UpdateAttributes:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateAttributes
      CodeUri: src/UpdateAttributes
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAuthorizedAPIPOSTcognitouserattributesedit:
          Type: Api
          Properties:
            Path: /cognito/user/attributes/edit
            Method: POST
            RestApiId: !Ref UserAuthorizedAPI
  UpdateAttributesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateAttributes}
      RetentionInDays: 7
  VerifyAttribute:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: VerifyAttribute
      CodeUri: src/VerifyAttribute
      Handler: handler.handler
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: !GetAtt LambdaCognitoRole.Arn
      Environment:
        Variables:
          USER_POOL_ID: !ImportValue userPoolId
          CLIENT_ID: !ImportValue userPoolClientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        UserAuthorizedAPIPOSTcognitouserattributesverify:
          Type: Api
          Properties:
            Path: /cognito/user/attributes/verify
            Method: POST
            RestApiId: !Ref UserAuthorizedAPI
  VerifyAttributeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${VerifyAttribute}
      RetentionInDays: 7
Transform: AWS::Serverless-2016-10-31
Parameters:
  clientSecret:
    Type: String
    Description: UserPoolClient secret
    Default: XXXX
Outputs:
  UserAPIId:
    Value: !Ref UserAPI
    Description: UserAPI ID
    Export:
      Name: userAPIId
  UserAuthorizedAPIId:
    Value: !Ref UserAuthorizedAPI
    Description: UserAuthorizedAPI ID
    Export:
      Name: userAuthorizedAPIId