Resources:
  UserAPIProdUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub ${AWS::StackName}-userapi-prod-plan
      Description: Usage free plan for UserAPIUsagePlan
      Quota:
        Limit: !Ref limitUserAPIProdUsagePlan
        Period: MONTH
      Throttle:
        BurstLimit: !Ref burstLimitUserAPIProdUsagePlan
        RateLimit: !Ref rateLimitUserAPIProdUsagePlan
      ApiStages:
        - ApiId: !ImportValue userAPIId
          Stage: prod
        - ApiId: !ImportValue userAPIId
          Stage: dev
  UserAPIProdApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: API key for UserAPIFreeApiKey
      Enabled: true
      Name: !Sub ${AWS::StackName}-userapi-prod-apikey
  UserAPIProdUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyType: API_KEY
      UsagePlanId: !Ref UserAPIProdUsagePlan
      KeyId: !Ref UserAPIProdApiKey
Transform: AWS::Serverless-2016-10-31
Parameters:
  limitUserAPIProdUsagePlan:
    Type: Number
    Description: maximum number of requests
    Default: 5000
  burstLimitUserAPIProdUsagePlan:
    Type: Number
    Description: allows more requests through for a period of time
    Default: 200
  rateLimitUserAPIProdUsagePlan:
    Type: Number
    Description: request rate limit.
    Default: 100
