version: '3.8'
services:
  presentation:
    build:
      context: ./frontend/NextJs
      dockerfile: Dockerfile
    image: next_js
    container_name: next_js
    restart: always
    tty: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    extra_hosts:
      - local_dev:${HOST_IP}
    #command:
  application:
    build:
      context: ./backend/Django_RESTFrameWork
      dockerfile: Dockerfile
    image: django_drf
    container_name: django_drf
    restart: always
    tty: true
    environment:
      - SECRET_KEY=${SECRET_KEY}
    expose:
      - 8081
    ports:
      - '8081:8081'
    extra_hosts:
      - local_dev:${HOST_IP}
    volumes:
      - ./backend/Django_RESTFrameWork/Foundation_Building/db.sqlite3:/usr/src/app/db.sqlite3
    #command:
