version: '3.8'
services:
  presentation:
    build:
      context: ./frontend/NextJs
      dockerfile: Dockerfile
    image: kamegin4/foundation-building:next_js
    container_name: next_js
    restart: always
    tty: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    #extra_hosts:
    #  - local_dev:${HOST_IP}
    #command:
  application:
    build:
      context: ./backend/Django_RESTFrameWork
      dockerfile: Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - DJANGO_DEBUG=${DJANGO_DEBUG}
        - ELASTICACHE_ENDPOINT=${ELASTICACHE_ENDPOINT}
        - RDS_USER=${RDS_USER}
        - RDS_PASSWORD=${RDS_PASSWORD}
        - RDS_HOST=${RDS_HOST}
        - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
        - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
        - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    image: kamegin4/foundation-building:django_rf
    container_name: django_rf
    restart: always
    tty: true
    #environment:
    expose:
      - 8081
    ports:
      - '8081:8081'
    #extra_hosts:
    #  - local_dev:${HOST_IP}
    #volumes:
    #  - ./backend/Django_RESTFrameWork/Foundation_Building/db.sqlite3:/usr/src/app/db.sqlite3
    #command:
