services:
  web:
    build:
      context: ./infra/Nginx
      dockerfile: Dockerfile
      args:
        - HOST_DOMAIN=${HOST_DOMAIN}
        - APP_DOMAIN=${APP_DOMAIN}
    image: ${REPOSITORY_URI}:nginx
    container_name: nginx
    restart: always
    tty: true
    #privileged: true
    depends_on:
    #  - presentation
      - application
    #environment:
    expose:
      - 80
      - 443
    ports:
      - '80:80'
      - '443:443'
    #volumes:
    #command:
  presentation:
    build:
      context: ./frontend/NextJs
      dockerfile: Dockerfile
    image: ${REPOSITORY_URI}:next_js
    container_name: next_js
    restart: always
    tty: true
    #privileged: true
    expose:
      - 8080
    ports:
      - '8080:8080'
    #command:
  application:
    build:
      context: ./backend/Django_RESTFramework
      dockerfile: Dockerfile
      args:
        - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
        - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
        - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    image: ${REPOSITORY_URI}:django_rf
    container_name: django_rf
    restart: always
    tty: true
    privileged: true
    #environment:
    expose:
      - 8081
    ports:
      - '8081:8081'
    volumes:
      - ./backend/Django_RESTFramework/Foundation_Building/db.sqlite3:/usr/src/app/Foundation_Building/db.sqlite3
    #command:
