version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "clientSecret=\"clientSecret\" globalIP=\"globalIP\" vpcId=\"vpcId\" publicSecurityGroupId=\"publicSecurityGroupId\" efsSecurityGroupId=\"efsSecurityGroupId\" publicSubnet1Id=\"publicSubnet1Id\" publicSubnet2Id=\"publicSubnet2Id\" elbTargetGroupArn=\"elbTargetGroupArn\" dockerCredentialsParameter=\"{\\\"username\\\":\\\"XXXXXX\\\",\\\"password\\\":\\\"XXXXXXX\\\"}\""
