Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
        - preferred_username
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      AutoVerifiedAttributes:
        - email
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
  Login:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Login
      CodeUri: src/Login
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERPOOL_USER_POOL_ID: '!Ref UserPool'
          USERPOOL_USER_POOL_ARN: '!GetAtt UserPool.Arn'
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
          USER_POOL_ID: !Ref userPoolId
          CLIENT_ID: !Ref clientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        CognitoPOSTcognitologin:
          Type: Api
          Properties:
            Path: /cognito/login
            Method: POST
            RestApiId: !Ref Cognito
  LoginLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Login}
  Logout:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Logout
      CodeUri: src/Logout
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        CognitoPOSTcognitologout:
          Type: Api
          Properties:
            Path: /cognito/logout
            Method: POST
            RestApiId: !Ref Cognito
      Environment:
        Variables:
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
          USER_POOL_ID: !Ref userPoolId
          CLIENT_ID: !Ref clientId
          CLIENT_SECRET: !Ref clientSecret
  LogoutLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Logout}
  Configuration:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Configuration
      CodeUri: src/Configuration
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
          USER_POOL_ID: !Ref userPoolId
          CLIENT_ID: !Ref clientId
          CLIENT_SECRET: !Ref clientSecret
      Events:
        CognitoAuthorizedPOSTcognitoconfiguration:
          Type: Api
          Properties:
            Path: /cognito/configuration
            Method: POST
            RestApiId: !Ref CognitoAuthorized
  ConfigurationLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${Configuration}
  Cognito:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Cognito
      StageName: Prod
      Auth:
        ResourcePolicy:
          IpRangeWhitelist:
            - !Ref globalIP
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /cognito/login:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Login.Arn}/invocations
              responses: {}
          /cognito/logout:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Logout.Arn}/invocations
              responses: {}
          /cognito/signup:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SignUp.Arn}/invocations
              responses: {}
          /cognito/confirm-signup:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmSignUp.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''*'''
        AllowMethods: '''*'''
        MaxAge: 5
  SignUp:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SignUp
      CodeUri: src/SignUp
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        CognitoPOSTcognitosignup:
          Type: Api
          Properties:
            Path: /cognito/signup
            Method: POST
            RestApiId: !Ref Cognito
      Environment:
        Variables:
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
          USER_POOL_ID: !Ref userPoolId
          CLIENT_ID: !Ref clientId
          CLIENT_SECRET: !Ref clientSecret
  SignUpLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${SignUp}
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      GenerateSecret: true
  ConfirmSignUp:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ConfirmSignUp
      CodeUri: src/ConfirmSignUp
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        CognitoPOSTcognitoconfirmsignup:
          Type: Api
          Properties:
            Path: /cognito/confirm-signup
            Method: POST
            RestApiId: !Ref Cognito
      Environment:
        Variables:
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
          USER_POOL_ID: !Ref userPoolId
          CLIENT_ID: !Ref clientId
          CLIENT_SECRET: !Ref clientSecret
  ConfirmSignUpLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ConfirmSignUp}
  CognitoAuthorized:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: CognitoAuthorized
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /cognito/configuration:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Configuration.Arn}/invocations
              responses: {}
          /cognito/confirm-configuration:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmConfiguration.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Auth:
        Authorizers:
          Cognito:
            UserPoolArn: !GetAtt UserPool.Arn
        ResourcePolicy:
          IpRangeWhitelist:
            - !Ref globalIP
        DefaultAuthorizer: Cognito
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''*'''
        AllowMethods: '''*'''
        MaxAge: 5
  ConfirmConfiguration:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ConfirmConfiguration
      CodeUri: src/ConfirmConfiguration
      Handler: handler.handler
      Runtime: python3.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERPOOLCLIENT_USER_POOL_CLIENT_ID: !Ref UserPoolClient
      Events:
        CognitoAuthorizedPOSTcognitoconfirmconfiguration:
          Type: Api
          Properties:
            Path: /cognito/confirm-configuration
            Method: POST
            RestApiId: !Ref CognitoAuthorized
  ConfirmConfigurationLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ConfirmConfiguration}
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: MyECSCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: {}
  Service:
    Type: AWS::ECS::Service
    Properties: {}
Transform: AWS::Serverless-2016-10-31
Parameters:
  userPoolId:
    Type: String
  clientId:
    Type: String
  clientSecret:
    Type: String
  globalIP:
    Type: String