Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Ref glueJobScriptS3
      DefaultArguments:
        '--job-bookmark-option': job-bookmark-disable
        '--enable-auto-scaling': 'true'
        '--enable-job-insights': 'true'
        '--enable-metrics': 'true'
        '--enable-observability-metrics': 'true'
        '--enable-continuous-cloudwatch-log': 'true'
        '--enable-glue-datacatalog': 'true'
        '--TempDir': !Ref glueJobS3TempDir
        '--job-language': python
        '--extra-py-files': !Ref glueJobExtraPyS3Files
        '--spark-event-logs-path': !Ref glueJobS3SparkLog
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: GlueJob
      Role: !Ref glueJobRoleArn
      GlueVersion: '4.0'
      WorkerType: G.1X
      NumberOfWorkers: 10
      ExecutionClass: FLEX
      Connections:
        - !Ref glueConnectionName
Transform: AWS::Serverless-2016-10-31
Parameters:
  glueJobScriptS3:
    Type: String
    Default: s3://foundation-building-app-objects-XXXX/Glue/scripts/FoundationBuilding_Glue_Job.py
  glueJobS3TempDir:
    Type: String
    Default: s3://foundation-building-app-objects-XXXX/Glue/temporary/
  glueJobExtraPyS3Files:
    Type: String
    Default: s3://aws-glue-studio-transforms-200493242866-prod-ap-northeast-1/gs_common.py,s3://aws-glue-studio-transforms-200493242866-prod-ap-northeast-1/gs_flatten.py
  glueJobS3SparkLog:
    Type: String
    Default: s3://foundation-building-app-objects-XXXX/Glue/sparkHistoryLogs/
  glueJobRoleArn:
    Type: String
    Default: arn:aws:iam::XXXX:role/GlueRole
  glueConnectionName:
    Type: String
    Default: ConnectionGlueRDS