Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineMode: provisioned
      DBClusterIdentifier: serverless-v2-aurora-postgresql
      MasterUsername: foundation_building
      ManageMasterUserPassword: true
      MasterUserSecret:
        KmsKeyId: !Ref AuroraKey
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 4
      StorageEncrypted: true
      EnableHttpEndpoint: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue rdsSecurityGroupId
      EnableCloudwatchLogsExports:
        - postgresql
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      DBInstanceClass: db.serverless
      DBClusterIdentifier: !Ref DBCluster
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
        - !ImportValue privateSubnet1Id
        - !ImportValue privateSubnet2Id
  ObjectStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-objects-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        BlockPublicAcls: true
        BlockPublicPolicy: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - !Sub
                - http://${appDomain}
                - appDomain: !ImportValue appDomain
              - !Sub https://${hostDomain}
            ExposedHeaders:
              - ETag
              - x-amz-meta-custom-header
            Id: myCORSRuleId1
            MaxAge: 3600
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: foundation_building
  ObjectStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ObjectStorage
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Sid: default-policy
            Effect: Deny
            Action: '*'
            Principal: '*'
            Resource:
              - !GetAtt ObjectStorage.Arn
              - !Sub ${ObjectStorage.Arn}/*
            Condition:
              Bool:
                aws:SecureTransport: 'false'
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service:
                - cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${ObjectStorage}/*
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}
          - Sid: AllowGlue
            Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${ObjectStorage}/*
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
          - Sid: AllowVPC
            Effect: Allow
            Principal: '*'
            Action: s3:*
            Resource: !Sub arn:aws:s3:::${ObjectStorage}/*
            Condition:
              StringEquals:
                aws:SourceVpc: !ImportValue vpcId
  LoggingBucket:
    Type: AWS::S3::Bucket
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - logging.s3.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - /*
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt ObjectStorage.Arn
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          TargetOriginId: !GetAtt ObjectStorage.RegionalDomainName
          ViewerProtocolPolicy: allow-all
          CachePolicyId: !GetAtt CachePolicy.Id
        Enabled: true
        Origins:
          - DomainName: !GetAtt ObjectStorage.RegionalDomainName
            Id: !GetAtt ObjectStorage.RegionalDomainName
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        SigningBehavior: always
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4
        Name: ObjectStorageOAC
  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        MinTTL: 300
        MaxTTL: 31536000
        ParametersInCacheKeyAndForwardedToOrigin:
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          QueryStringsConfig:
            QueryStringBehavior: none
        DefaultTTL: 86400
        Name: CloudfrontCachePolicy
  ServerlessCache:
    Type: AWS::ElastiCache::ServerlessCache
    Properties:
      ServerlessCacheName: serverless-cache
      Engine: memcached
      Description: My Serverless memcached Cache
      KmsKeyId: !Ref ElasticCacheKey
      SecurityGroupIds:
        - !ImportValue elastiCacheSecurityGroupId
      SubnetIds:
        - !ImportValue privateSubnet1Id
        - !ImportValue privateSubnet2Id
  ElasticCacheKey:
    Type: AWS::KMS::Key
    Properties:
      Description: My Symmetric Encryption Key
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-ElasticCacheKey
        Statement:
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                - !Sub arn:aws:sts::${AWS::AccountId}:federated-user/${userName}
            Action:
              - kms:*
            Resource: '*'
          - Sid: Allow use of the key from VPC
            Effect: Allow
            Principal: '*'
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:sourceVpc: !ImportValue vpcId
          - Sid: Allow use of the key from ElastiCache
            Effect: Allow
            Principal:
              Service:
                - elasticache.amazonaws.com
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
  AuroraKey:
    Type: AWS::KMS::Key
    Properties:
      Description: My Symmetric Encryption Key
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-AuroraKey
        Statement:
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
                - !Sub arn:aws:sts::${AWS::AccountId}:federated-user/${userName}
            Action:
              - kms:*
            Resource: '*'
          - Sid: Allow use of the key from VPC
            Effect: Allow
            Principal: '*'
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:sourceVpc: !ImportValue vpcId
          - Sid: Allow use of the key from rds
            Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
Transform: AWS::Serverless-2016-10-31
Parameters:
  userName:
    Description: User Name
    Type: String
    Default: XXXX
  hostDomain:
    Description: Host Domain
    Type: String
    Default: foundation-building.XXXX.com
Outputs:
  objectStorageName:
    Value: !Ref ObjectStorage
    Description: ObjectStorage Name
    Export:
      Name: objectStorageName
