Resources:
  ObjectStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-object-storage
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        BlockPublicAcls: true
        BlockPublicPolicy: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - !Sub
                - http://${AppDomain}
                - AppDomain: !ImportValue appDomain
            ExposedHeaders:
              - ETag
              - x-amz-meta-custom-header
            Id: myCORSRuleId1
            MaxAge: 3600
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: foundation-building
      ObjectLockEnabled: false
  ObjectStorageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ObjectStorage
      PolicyDocument:
        Id: RequireEncryptionInTransit
        Version: '2012-10-17'
        Statement:
          - Sid: RequireSecureTransport
            Effect: Deny
            Action: '*'
            Principal: '*'
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage]]
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: 'false'
          - Sid: AllowCloudFront
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage]]
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage, '/*']]
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
          - Sid: AllowGlueService
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: s3:*
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage]]
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage, '/*']]
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
          - Sid: AllowVPC
            Effect: Allow
            Principal: '*'
            Action: s3:*
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage]]
              - !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage, '/*']]
            Condition:
              StringEquals:
                aws:SourceVpc: !ImportValue vpcId
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        BlockPublicAcls: true
        BlockPublicPolicy: true
      ObjectLockEnabled: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - /*
            Condition:
              ArnLike:
                aws:SourceArn: !Join ['', ['arn:aws:s3:::', !Ref ObjectStorage]]
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
Outputs:
  ObjectStorageName:
    Value: !Ref ObjectStorage
    Description: ObjectStorage Name
    Export:
      Name: objectStorageName
