# Generated by Django 5.0.2 on 2024-02-28 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElastiCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=5120)),
                ('value', models.CharField(max_length=51200)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elasticache_allowed_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'updated_at', 'create_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=256)),
                ('result', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('elasticache', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_elasticache', to='mini_aws.elasticache')),
            ],
            options={
                'ordering': ['user_name', 'updated_at', 'create_at'],
            },
        ),
    ]
