# Generated by Django 5.0.2 on 2024-04-10 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('user_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['user_name', 'updated_at', 'create_at'],
            },
        ),
        migrations.CreateModel(
            name='ElastiCache',
            fields=[
                ('id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=5120, unique=True)),
                ('value', models.CharField(max_length=51200)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elasticache', to='mini_aws.userresults')),
            ],
            options={
                'ordering': ['key', 'updated_at', 'create_at'],
                'unique_together': {('user_results', 'key')},
            },
        ),
    ]
