# Generated by Django 5.0.2 on 2024-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticache',
            name='key',
            field=models.CharField(max_length=5120),
        ),
    ]
