# Generated by Django 5.0.2 on 2024-02-28 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_aws', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticache',
            name='key',
            field=models.CharField(max_length=5120, unique=True),
        ),
        migrations.AlterField(
            model_name='elasticache',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elasticache', to=settings.AUTH_USER_MODEL),
        ),
    ]
