# Generated by Django 5.0.2 on 2024-03-17 20:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elasticache',
            name='id',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
