# Generated by Django 5.0.2 on 2024-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_aws', '0002_alter_elasticache_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elasticache',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='elasticache',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
