# Generated by Django 5.0.2 on 2024-03-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_aws', '0002_alter_elasticache_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elasticache',
            name='owner',
        ),
    ]
