Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineMode: provisioned
      DBClusterIdentifier: serverless-v2-aurora-postgresql
      DatabaseName: !Ref dbName
      MasterUsername: !Ref masterUsername
      ManageMasterUserPassword: true
      MasterUserSecret:
        KmsKeyId: !Ref AuroraKey
      ServerlessV2ScalingConfiguration:
        MinCapacity: 0.5
        MaxCapacity: 4
      StorageEncrypted: true
      EnableHttpEndpoint: true
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !ImportValue rdsSecurityGroupId
      EnableCloudwatchLogsExports:
        - postgresql
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-postgresql
      DBInstanceClass: db.serverless
      PubliclyAccessible: false
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      AllowMajorVersionUpgrade: true
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
        - !ImportValue privateSubnet1Id
        - !ImportValue privateSubnet2Id
  AuroraKey:
    Type: AWS::KMS::Key
    Properties:
      Description: My Symmetric Encryption Key
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-AuroraKey
        Statement:
          - Sid: AllowRoot
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource: '*'
          - Sid: AllowUser
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:sts::${AWS::AccountId}:federated-user/${userName}
            Action:
              - kms:*
            Resource: '*'
          - Sid: AllowVPC
            Effect: Allow
            Principal: '*'
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:SourceVpc: !ImportValue vpcId
          - Sid: AllowService
            Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - kms:*
            Resource: '*'
            Condition:
              StringEquals:
                aws:ResourceAccount: !Ref AWS::AccountId
Transform: AWS::Serverless-2016-10-31
Parameters:
  userName:
    Description: User Name
    Type: String
    Default: XXXX
  masterUsername:
    Description: DB Master Username
    Type: String
    Default: foundation_building
  dbName:
    Description: DB name
    Type: String
    Default: foundation_building
Outputs:
  DBEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
    Description: DBEndpoint
    Export:
      Name: dbEndpoint
  DBPort:
    Value: !GetAtt DBInstance.Endpoint.Port
    Description: DBPort
    Export:
      Name: dbPort
  MasterUserSecret:
    Value: !GetAtt DBCluster.MasterUserSecret.SecretArn
    Description: MasterUserSecret
    Export:
      Name: masterUserSecret
