Resources:
  ProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: progress_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: 'N'
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 100
        MaxWriteRequestUnits: 100
      KeySchema:
        - AttributeName: progress_id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserGSI
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ContributorInsightsSpecification:
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TimeToLiveSpecification:
        AttributeName: created_at
        Enabled: true
      ResourcePolicy:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowVPC
              Effect: Allow
              Principal: '*'
              Action: dynamodb:*
              Resource: '*'
              Condition:
                StringEquals:
                  aws:SourceVpc:
                    - !ImportValue vpcId
            - Sid: AllowService
              Effect: Allow
              Action: dynamodb:*
              Principal: '*'
              Resource: '*'
              Condition:
                StringEquals:
                  aws:ResourceAccount: !Ref AWS::AccountId
                  aws:PrincipalServiceName:
                    - lambda.amazonaws.com
Transform: AWS::Serverless-2016-10-31
Outputs:
  ProgressTableName:
    Value: !Ref ProgressTable
    Description: ProgressTable Name.
    Export:
      Name: progressTableName
