# Generated by Django 5.1 on 2024-08-24 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationaldata',
            name='comment',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='relationaldata',
            name='key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='relationaldata',
            name='meta_key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='relationaldata',
            name='meta_value',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='relationaldata',
            name='value',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=256),
        ),
    ]
