# Generated by Django 5.1 on 2024-08-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_app', '0003_alter_relationaldata_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expires',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
